apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ventas
  namespace: innovatech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-ventas
  template:
    metadata:
      labels:
        app: backend-ventas
    spec:
      containers:
        - name: backend-ventas
          image: TU_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/innovatech-backend-ventas:eks-v1
          ports:
            - containerPort: 8080
          env:
            - name: DB_ENDPOINT
              value: "mysql-db"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "innovatech"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 15
            